name: test
on:
  push:
    # Exclude unrelated file changes from triggering workflow
    # Ref: https://stackoverflow.com/questions/69557828/stop-triggering-github-actions-on-updating-some-files-in-repository
    paths-ignore:
      - README.md
      - info.yaml
      - docs/*
      - .github/workflows/gds.yaml
      - .github/workflows/docs.yaml
  workflow_dispath:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # use SSH private key to be able to checkout git submodule containing AOC inputs
          # Ref: https://github.com/orgs/community/discussions/50130
          ssh-key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r test/requirements.txt

      - name: Run tests
        run: |
          cd test
          make clean
          make
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/results.xml"
        if: always()

      - name: upload vcd
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-vcd
          path: |
            test/tb.vcd
            test/results.xml
